### ISSUE TITLE
Simple migration

### ISSUE THREAD

**Issue by stevehipwell** [utkuozdemir/pv-migrate#27]
Have you considered simple migrations such as Helm chart renames (Prometheus operator) or cluster rebuild where no data has to actually move?

I've done this manually on AWS in the past by creating the new PV and PVC, getting the YAML, deleting the new PV and PVC and then recreating them with reference to the old EBS volumes substituted in.

**Comment by utkuozdemir** [comment]
Thanks for the suggestion 😊

If I understand correctly you mean [statically provisioning](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#static) a new volume which would point to the source volume. I gave it a thought, and I think there are couple of problems with that:
- It is a _move_ operation rather than _copy_ - so it is inconsistent with the behavior of other strategies
- Not sure if we can do it reliably, its success would depend on the underlying storage solution.

So it's not something I would consider implementing at this time. However, if I meet similar requests/need over time, I could reevaluate it.

**Comment by stevehipwell** [comment]
Thanks for the reply @utkuozdemir. You're right that it's either a move operation or you're dependent on the underlying infrastructure to snapshot the volume.
